import Header from '@/components/layout/Header'
import './globals.css'
import { inter, pacifico } from '@/utils/font'
import { cn } from '@/utils/style'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: {
  children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={cn(inter.variable, pacifico.variable, 'font-inter')}>
                <Header />
                <main className='w-full h-[calc(100vh-6rem)]'>{children}</main>
            </body>
        </html>
    )
}
